AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ## 🔹 Parámetro para el Nombre del Entorno
  Parameters:
    EnvironmentName:
      Type: String
      Description: "Nombre del entorno (dev, staging, prod)"
  ##ECR rol
  ECRRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "ECRRepositoryRole-${EnvironmentName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecr.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "ECRFullAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:CreateRepository"
                  - "ecr:DeleteRepository"
                  - "ecr:DescribeRepositories"
                  - "ecr:BatchGetImage"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:PutImage"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:UploadLayerPart"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:SetRepositoryPolicy"
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub "ECRRole-${EnvironmentName}"

  ##Repository ECR
  ECRRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "nats-surveyor"
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Eliminar imágenes sin etiqueta después de 30 días",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt ECRRole.Arn
            Action:
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
