AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvironmentName:
    Type: String
    Description: "Nombre del entorno (dev, staging, prod)"

Resources:
  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "SURVEYOR"
      ServiceRole: !ImportValue IAMRole2Arn
      Source:
        Type: "CODEPIPELINE"
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              commands:
                - echo "Logging in to Amazon ECR..."
                - aws ecr get-login-password --region ${AWS::Region} | docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/nats-surveyor
            pre_build:
              commands:
                - echo "Building the Docker image..."
                - docker build --no-cache -t nats-surveyor .
            build:
              commands:
                - echo "Tagging the Docker image..."
                - docker tag nats-surveyor:latest ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/nats-surveyor:latest
            post_build:
              commands:
                - echo "Pushing the Docker image to ECR..."
                - docker push ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/nats-surveyor:latest
                - echo "Build completed on `date`"
                - echo "Creating imagedefinitions.json for ECS deployment"
                - printf '[{"name":"nats-surveyor","imageUri":"%s:%s"}]' ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/nats-surveyor latest > imagedefinitions.json
                - echo "Starting deployment using CodeDeploy"
          artifacts:
            files:
              - imagedefinitions.json
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:7.0"
        ImagePullCredentialsType: "CODEBUILD"
        PrivilegedMode: true
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: "CommitId"
            Type: "PLAINTEXT"
            Value: "latest"
      Artifacts:
        Type: "CODEPIPELINE"
      Cache:
        Type: "NO_CACHE"
      TimeoutInMinutes: 60
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
      VpcConfig:
        VpcId: !ImportValue VPCId
        Subnets:
          - !ImportValue PublicSubnet1Id
          - !ImportValue PublicSubnet2Id
        SecurityGroupIds:
          - !ImportValue SecurityGroupId

Outputs:
  ECRRepositoryUri:
    Description: "ECR Repository URI"
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/nats-surveyor"