AWSTemplateFormatVersion: "2010-09-09"
Description: Crea una VPC con NAT Gateways integrados para subredes públicas y privadas

Parameters:
  VpcCIDR:
    Description: CIDR block para la VPC
    Type: String
    Default: "10.0.0.0/16"
  PublicSubnet1CIDR:
    Description: CIDR block para la primera subred pública
    Type: String
    Default: "10.0.1.0/24"
  PublicSubnet2CIDR:
    Description: CIDR block para la segunda subred pública
    Type: String
    Default: "10.0.2.0/24"
  PrivateSubnet1CIDR:
    Description: CIDR block para la primera subred privada
    Type: String
    Default: "10.0.3.0/24"
  PrivateSubnet2CIDR:
    Description: CIDR block para la segunda subred privada
    Type: String
    Default: "10.0.4.0/24"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
    Tags:
      - Key: "Name"
        Value: "MiVPC"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Tags:
      - Key: "Name"
        Value: "MiInternetGateway"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1CIDR
      AvailabilityZone: !Select [0, !GetAZs ""]
    Tags:
      - Key: "Name"
        Value: "Publica 1"

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2CIDR
      AvailabilityZone: !Select [1, !GetAZs ""]
    Tags:
      - Key: "Name"
        Value: "Publica 2"

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1CIDR
      AvailabilityZone: !Select [0, !GetAZs ""]
    Tags:
      - Key: "Name"
        Value: "Privada 1"

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2CIDR
      AvailabilityZone: !Select [1, !GetAZs ""]
    Tags:
      - Key: "Name"
        Value: "Privada 2"

  NatGatewayEIP1:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: "vpc"
    Tags:
      - Key: "Name"
        Value: "EIP para NAT"

  NatGateway1:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt NatGatewayEIP1.AllocationId
      SubnetId: !Ref PublicSubnet1
    Tags:
      - Key: "Name"
        Value: "MiNATGateway"

  PrivateSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
    Tags:
      - Key: "Name"
        Value: "RT Privada 1"

  PrivateSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
    Tags:
      - Key: "Name"
        Value: "RT Privada 2"

  PrivateSubnet1Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref PrivateSubnet1RouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NatGateway1

  PrivateSubnet2Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref PrivateSubnet2RouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NatGateway1

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC
  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet1
  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Value: !Ref PublicSubnet2
  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Value: !Ref PrivateSubnet1
  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Value: !Ref PrivateSubnet2
